import { defineConfig } from 'orval'

export default defineConfig({
  'casa-dana-api-file': {
    input: 'src/api/specifications/openapi.yaml',
    output: {
      mode: 'tags-split',
      target: 'src/api/endpoints/',
      schemas: 'src/api/models',
      client: 'react-query',
      mock: false,
      prettier: true,
      override: {
        header: () => [`Generated by orval 🍺`, `Do not edit manually.`],
        mutator: {
          path: 'src/api/customAxiosInstance.ts',
          name: 'customAxiosInstance'
        }
      }
    }
  }
})
