import {
  HouseFront1,
  HouseFront2,
  HouseFront3,
  HouseBedRoom1,
  HouseBedRoom2,
  HouseBedRoom3,
  HouseBedRoom1_1,
  HouseJacuzzi1,
  HouseJacuzzi2,
  HouseKitchen1,
  HouseKitchen2,
  HouseLivingRoom1,
  HouseLivingRoom2,
  HouseLivingRoom3,
  HouseRoofTop1,
  HouseRoofTop2,
  HouseRoofTop3,
  HouseRoofTop4,
  HouseRoofTop5,
  HouseRoofTop6,
  HouseBathRoom
} from '../assets/photos'

export const img = [
  HouseFront1,
  HouseFront2,
  HouseFront3,
  HouseBedRoom1,
  HouseBedRoom2,
  HouseBedRoom3,
  HouseBedRoom1_1,
  HouseBathRoom,
  HouseJacuzzi1,
  HouseJacuzzi2,
  HouseKitchen1,
  HouseKitchen2,
  HouseLivingRoom1,
  HouseLivingRoom2,
  HouseLivingRoom3,
  HouseRoofTop1,
  HouseRoofTop2,
  HouseRoofTop3,
  HouseRoofTop4,
  HouseRoofTop5,
  HouseRoofTop6
]
