/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

export interface ProblemDetails {
  /** @nullable */
  type?: string | null
  /** @nullable */
  title?: string | null
  /** @nullable */
  status?: number | null
  /** @nullable */
  detail?: string | null
  /** @nullable */
  instance?: string | null
  [key: string]: unknown
}
