/**
 * Generated by orval 🍺
 * Do not edit manually.
 */

export interface RegisterModel {
  /** @nullable */
  email: string | null
  /** @nullable */
  password: string | null
  /** @nullable */
  firstName: string | null
  /** @nullable */
  lastName: string | null
}
